import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { QueryProvider } from "@/providers/query-provider";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const inter = Recursive({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = (await import(`../../messages/${locale}.json`)).default;

  return (
    <html
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        inter.variable
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            <NextIntlClientProvider
              locale={locale}
              messages={messages}
            >
              {children}
            </NextIntlClientProvider>
          </NextThemesProvider>
        </QueryProvider>
      </body>
    </html >
  );
}